// This is my JavaScript to generate the randomly selected abilites

const ability1 = [
    "Until end of turn, up to one target creature gets +1\/+1 and gains first strike, vigilance, and lifelink.",
    "Distribute three +1\/+1 counters among one, two, or three target creatures you control.",
    "Destroy target noncreature permanent.",
    "Create two 3\/1 red Elemental creature tokens with haste. Exile them at the beginning of the next end step.",
    "Create three 1\/1 white Soldier creature tokens.",
    "Create a 3\/3 black Beast creature token with deathtouch.",
    "The next spell you cast this turn has cascade",
    "Reveal the top five cards of your library. Put all creature cards revealed this way into your hand and the rest on the bottom of your library in any order.",
    "During target opponent\'s next turn, creatures that player controls attack Urza if able.",
    "Put a loyalty counter on Urza for each creature target opponent controls.",
    "Until your next turn, whenever a creature an opponent controls attacks, it gets - 1\/-0 until end of turn.",
    "Target player exiles a card from their hand.",
    "Reveal the top card of your library. If it\'s a land card, put it onto the battlefield. Otherwise, put it into your hand.",
    "Target land you control becomes a 4\/4 Elemental creature with trample.It\'s still a land.",
    "Draw a card, then add one mana of any color.",
    "Until end of turn, Urza becomes a legendary 4\/4 red Dragon creature with flying, indestructible, and haste. (He doesn\'t lose loyalty while he\'s not a planeswalker.)",
    "Until your next turn, creatures you control get +1\/+0 and gain lifelink.",
    "Look at the top five cards of your library.You may reveal an artifact card from among them and put it into your hand.Put the rest on the bottom of your library in any order.",
    "Urza deals 3 damage to any target.",
    "Until your next turn, whenever a creature deals combat damage to Urza, destroy that creature.",
    "Add X mana in any combination of colors, where X is the number of creatures you control.",
    "Whenever one or more creatures you control deal combat damage to a player, draw a card.",
    "Create a 2\/2 black pirate creature token with Menace.",
    "You gain life equal to the greatest power among creatures you control.",
    "Draw a card.",
    "Each opponent discards a card and loses 3 life.",
    "Put a loyalty counter on Urza, Academy Headmaster for each creature you control.",
    "Urza, Academy Headmaster deals 1 damage to target player and each creature they control.",
    "Draw a card. At the beginning of the next endstep, untap two lands.",
    "Untap up to one target artifact or creature.",
    "Add two mana of any color to your mana pool. Urza, Academy Headmaster deals 2 damage to target player.",
    "Target creature can\'t be blocked this turn.",
    "Target creature gets +2\/+2 until end of turn.",
    "Look at the top 3 cards of your library, you may put a creature card from among them into your hand and the rest into your graveyard.",
    "Create a 1\/1 colorless Thopter artifact creature token with flying.",
    "You may discard a card. If you do, draw a card.",
    "You gain 1 life for each loyalty counter on Urza, Academy Headmaster.",
    "You gain 1 life for each creature you control.",
    "Target player loses 2 life.",
    "Urza, Academy Headmaster deals 1 damage to each opponent and each creature your opponents control.",
    "Put two +1\/+1 counters on up to one target creature.",
    "Untap each enchanted permanent you control.",
    "Discard a card, then draw a card. If a land card was discarded this way draw an additional card.",
    "Look at the top 2 cards of your library, put one into your hand and the other into your graveyard.",
    "You may sacrifice another permanent. If you do, you gain 1 life and draw a card.",
    "Draw a card.",
    "Add one mana of any color, creature spells you cast this turn gain Riot.",
    "Put a +1\/+1 counter on target creature. That creature gains Menace and Deathtouch until end of turn.",
    "You gain 2 life. Draw a card.",
    "Target player puts the top 2 cards of their library into their graveyard. Draw a card.",
    "You gain hexproof until your next turn.",
    "Destroy target creature. It\'s controller draws 2 cards.",
    "Exile the top card of your library. You can play it this turn.",
    "Urza, Academy Headmaster deals 2 damage to any target.",
    "Create a 2\/2 green Wolf creature token.",
    "Put a +1\/+1 counter on target creature.",
    "You gain 4 life.",
    "Put three +1\/+1 counters on target noncreature land. Untap it. It becomes a 0\/0 Elemental creature with vigilance and haste. It\'s still a land.",
    "Scry 1",
    "Creature spells you cast this turn can\'t be countered.",
    "Until your next turn, prevent all damage dealt to and dealt by target permanent an opponent controls.",
    "Untap target permanent.",
    "Target creature gains +2\/+1 and haste until end of turn.",
    "Urza X damage to each opponent, where X is the number of artifacts you control.",
    "You gain life equal to the number of creatures and planeswalkers you control.",
    "Until your next turn, target creature gets - 2\/0 and loses flying.",
    "Target creature you control gains Deathtouch and Lifelink until end of turn. If it is a vampire put a +1\/+1 counter on it.",
    "Put a loyalty counter on each planeswalker you control.",
    "Distribute 2 +1\/+1 counters among any number of creatures.",
    "You gain 2 life. Put 2 +1\/+1 counters on target creature.",
    "Until your next turn, target creature gets - 5\/-0",
    "Create a food token.",
    "Target artifact or creature loses all abilities and becomes a green Elk creature with base power and toughness 3\/3",
    "Draw a card, discard a card.",
    "Create a 2\/3 blue and black Nightmare creature token with \"Whenever this creature attacks or blocks, each opponent exiles the top card of their library.\"",
    "Scry 3",
    "Create a 3\/3 green Beast creature token. Then put your choice of a vigilance counter, Trample counter, or reach counter on that token.",
    "Until end of turn, target creature gains indestructible and lifelink.",
    "Each player discards a card.",
    "Each player discards a card. Each opponent who can\'t loses 3 life.",
    "Discard your hand. The exile the top 4 cards of your library. Until end of turn you can play those cards.",
    "Up to one target creature gains +3\/+3 and has trample until end of turn.",
    "Up to one target creature gains exalted until end of turn.",
    "Return up to 1 target creature card in your graveyard to your hand.",
    "Urza deals 3 damage to each opponent.",
    "Reveal the top card of your library, if it is a creature card put it into your hand, otherwise put it on the bottom of your library.",
    "Target player exiles a card from their hand.",
    "Fateseal target player. (look at the top card of their library, you may put that card on the bottom of their library.)",
    "Draw three cards, then put two cards from your hand on top of your library in any order.",
    "Untap target land you control, you may have that land become a 3\/3 Elemental creature with Menace and Deathtouch until end of turn. It\'s still a land.",
    "You may sacrifice another creature or planeswalker. If you do draw two cards, then draw another card if that permanent was a commander.",
    "Create two 0\/1 black Thrull creature tokens.",
    "Choose target creature, until end of turn if that creature would deal damage to an opponent, it deals triple that much damage instead.",
    "Exile the top card of each player\'s library, you may cast spells from among them until end of turn.",
    "Put a +1\/+1 counter on target creature. Untap it. It gains Deathtouch until end of turn.",
    "Create a 1\/1 green Elf creature token.",
    "Put a ghostform counter on target creature. It gains \"When this creature dies or is put into exile, return it to it\'s owner\'s hand and create a 1\/1 white Spirit creature token.\"",
    "You draw a card and lose 1 life.",
    "Add three mana of any color, this mana can only be spent to cast instant or sorceries.",
    "You lose 1 life. Look at the top three cards of your library. Put one of them into your hand and the rest into your graveyard.",
    "You gain 2 life. The next instant or sorcery you cast this turn cost 2 less to cast.",
    "Draw two cards, then discard a card.",
    "Urza deals 1 damage to each opponent. If you have drawn three or more cards this turn, Urza deals 3 damage to each opponent instead.",
    "Surveil 2",
    "Create a 1\/1 black and green Insect creature token, then mill a card. If an creature card was milled this way, put a loyalty counter on Urza. Then repeat this process once.",
    "Target creature without first strike, double strike, or vigilance can\'t attack or block until your next turn.",
    "Draw two cards, then put a card from your hand on the bottom of your library.",
    "Creatures you control get +1\/+0 and gain haste until end of turn",
    "Venture into the dungeon. (Enter the first room or advance to the next room.)",
    "Reveal the top four cards of your library. Put all land cards revealed this way into your hand and the rest into your graveyard.",
    "Until your next turn, you may cast creature spells as though they had flash, and each creature you control enters the battlefield with an additional + 1\/+1 counter on it.",
    "Choose up to one target artifact, up to one target creature, and up to one target land. Untap the chosen permanents you control. Tap the chosen permanents you don\'t control. You gain 2 life.",
    "Create a 2\/2 black Zombie creature token. Mill two cards.",
    "Until end of turn, whenever a creature you control deals combat damage to a player, put a loyalty counter on Urza.",
    "Look at the top card of your library. You may reveal that card and put it into your hand. If you do, you lose life equal to its mana value.",
    "Exile the top card of your library.If it\'s red, you may cast it this turn.",
    "Creatures you control gain deathtouch until end of turn. Put a +1\/+1 counter on up to one target creature token you control.",
    "Put a +1\/+1 counter on up to one target creature. It gains first strike until end of turn.",
    "Draw a card. Then discard a card unless you attacked this turn.",
    "Tap up to one target artifact or creature.It doesn't untap during its controller\'s next untap step.",
    "Reveal the top three cards of your library. Put all nonland permanent cards revealed this way into your hand and the rest on the bottom of your library in any order.",
    "Choose up to one target creature. Put a +1\/+1 counter and a counter from among flying, first strike, lifelink, or vigilance on it.",
    "You may sacrifice a creature. If you do, search your library for a creature card with mana value equal to 1 plus the sacrificed creature\'s mana value, put it onto the battlefield, then shuffle.",
    "Mill five cards, then put any number of creature cards milled this way into your hand.",
    "Each opponent loses 2 life unless they discard a card.If you control a Demon or Devil, you gain 2 life.",
    "Draw a card, then scry 2",
    "Put three +1\/+1 counters on up to one target creature with trample or haste.",
    "Until your next turn, up to two target creatures each have base power and toughness 0\/3 and lose all abilities.",
    "During target player\'s next turn, each creature that player controls attacks if able.",
    "Until your next turn, up to one target creature gains vigilance and reach.",
    "Add X mana in any combination of colors, where X is the number of creatures you control.",
    "Up to one target creature gets -2\/-1 until your next turn.",
    "Draw a card, then put a card from your hand on top of your library.",
    "Target opponent exiles cards from the top of their library until they exile a nonland card. Until end of turn, you may cast that card without paying its mana cost.",
    "Return up to one target land card from your graveyard to your hand.",
    "Until your next turn, creatures can't attack you or planeswalkers you control unless their controller pays 2 life for each of those creatures.",
    "Create a tapped Powerstone token. (It\'s an artifact with \"{T}\: Add {C}. This mana can't be spent to cast a nonartifact spell.\")",
    "Create a 1\/1 red Monk creature token with prowess.",
    "Reveal the top card of your library. If it's a creature or planeswalker card, put it into your hand. Otherwise, you may put it on the bottom of your library.",
    "Create two 1\/1 green Squirrel creature tokens. They gain haste until end of turn.",
    "Scry 2",
    "You may tap an untapped artifact you control. If you do, draw a card.",
    "Exile up to one target artifact or creature. Return that card to the battlefield under its owner\'s control at the beginning of that player\'s next end step.",
    "Until your next turn, up to one target creature gets -3\/-",
    "You draw a card and you lose 1 life. Proliferate.",
    "Search your library for a basic Mountain card, reveal it, put it into your hand, then shuffle.",
    "Create an X\/X green Phyrexian Horror creature token, where X is Urza\'s loyalty.",
    "Each opponent loses 3 life and you gain 3 life.",
    "Up to one target creature can't attack or block until your next turn.",
    "Until your next turn, up to one target creature attacks a player each combat if able.",
    "Exile target creature or Equipment card with mana value less than Urza\'s loyalty from your graveyard. Create a token that\'s a copy of it. That token gains haste. Exile it at the beginning of the next end step.",
    "Discard a card, then draw a card.",
    "Untap up to one target creature.",
    "Create a 1\/1 white Soldier creature token with lifelink.",
    "Exile the top five cards of your library. Until the end of your next turn, you may cast an instant or sorcery spell from among those exiled cards.",
    "Add two mana in any combination of colors.",
    "Up to one target land you control becomes a 3\/3 Elemental creature with vigilance, hexproof, and haste until your next turn. It\'s still a land.",
    "Draw two cards. Then discard two cards unless you discard a creature card.",
    "Create a 1\/1 white Kor Soldier creature token. You may attach an Equipment you control to it.",
    "Look at the top two cards of your library. Put one of them into your hand and the other on the bottom of your library.",
    "Each opponent loses 1 life. You gain life equal to the life lost this way.",
    "Discard up to two cards, then draw that many cards.",
    "Create a 1\/1 green Elf Druid creature token with \"{T}\: Add {G}.\"",
    "Create a 1\/1 red Wizard creature token with \"{T}\: Add {R}. Spend this mana only to cast a planeswalker spell.\"",
    "You and target opponent each draw a card.",
    "Create a 0\/4 white Wall creature token with defender and flying.",
    "Up to two target planeswalkers you control phase out at the beginning of the next end step. (Treat them and anything attached to them as though they don\'t exist until your next turn.)",
    "Add {R} for each planeswalker you control.",
    "Exile the top card of your library face down and look at it. Create a 2\/2 colorless Spirit creature token. When that token leaves the battlefield, put the exiled card into your hand.",
    "Until end of turn, up to one target creature gets +1\/+1 and gains first strike, vigilance, and lifelink.",
    "During target opponent\'s next turn, creatures that player controls attack Urza if able.",
    "Each player draws a card.",
    "Until your next turn, whenever a creature an opponent controls attacks, it gets -1\/-0 until end of turn.",
    "Draw a card and reveal it. Remove a number of loyalty counters equal to that card's mana value from Urza, Academy Headmaster.",
    "Each opponent gets an emblem with \"At the beginning of your upkeep, this emblem deals 1 damage to you.\"",
    "Exile the top card of your library. You may cast that card. If you don't, Urza deals 2 damage to each opponent.",
    "Until end of turn, each planeswalker you control becomes a 4\/4 red Dragon creature and gains flying.",
    "Look at the top four cards of your library. You may reveal an enchantment card from among them and put that card into your hand. Put the rest on the bottom of your library in a random order.",
    "You gain 2 life. Add {U}, {R}, or {W}. Spend this mana only to cast a noncreature spell.",
    "Look at the top two cards of your library. Exile one of them and put the other into your hand.",
    "Create a 3\/2 red and white Spirit creature token.",
    "Create a 1\/1 black Vampire creature token with lifelink.",
    "Until your next turn, up to one target noncreature artifact becomes an artifact creature with power and toughness each equal to its mana value.",
    "Up to one other target creature you control gains your choice of vigilance, lifelink, or indestructible until end of turn.",
    "Create a 2\/2 black Zombie creature token.",
    "Look at the top card of your library. If it\'s a creature card, you may reveal it and put it into your hand.",
    "Exile up to two target cards from a single graveyard. You gain 2 life if at least one creature card was exiled this way.",
    "You draw a card. Each opponent exiles a card from their hand or a permanent they control.",
    "Until your next turn, you may cast sorcery spells as though they had flash.",
    "Create three 1\/1 white Soldier creature tokens.",
    "Draw two cards. Then discard two cards unless you discard an artifact card.",
    "Surveil 2, then exile a card from a graveyard.",
    "Draw two cards. If you\'ve committed a crime this turn, discard a card. Otherwise, discard two cards.",
    "Draw a card, then discard a card.",
    "You may exile a nonland card with mana value 3 or less from your hand. If you do, it becomes plotted.",
    "Put a +1\/+1 counter on each creature you control.",
    "Exile target permanent you own. Return it to the battlefield under your control at the beginning of the next end step",
    "You become the monarch.",
    "Draw a card, then discard a card at random.",
    "Role a D20, then create that many clue tokens.",
    "Draw a card. Target player mills a card.",
    "Search your library for a Swamp card, reveal it, put it into your hand, then shuffle.",
    "Destroy another target planeswalker.",
    "Create a 3\/3 black Beast creature token with deathtouch.",
    "Until end of turn, Urza becomes a legendary 4\/4 red Dragon creature with flying, indestructible, and haste. (He doesn\'t lose loyalty while he's not a planeswalker.)",
    "Reveal the top card of your library. If it\'s a land card, put it onto the battlefield. Otherwise, put it into your hand.",
    "Untap up to one target creature and up to one target land.",
];
const ability2 = [



    "Urza deals 3 damage to each creature.",
    "Gain control of target creature.",
    "Urza deals 4 damage to any target and you gain 4 life.",
    "Destroy target creature. You gain life equal to its toughness.",
    "You get an emblem with \"Creatures you control get + 1\/+1.\"",
    "You may put a creature card from your hand onto the battlefield.",
    "Draw three cards, then put a card from your hand on top of your library.",
    "Target player puts the top ten cards of their library into their graveyard.",
    "Reveal the top five cards of your library. An opponent separates those cards into two piles.Put one pile into your hand and the other on the bottom of your library in any order.",
    "Exile target permanent.",
    "At begining of your endstep, all permanents you control phase out. Until your next turn, your life total can\'t change and you gain protection from everything.",
    "Reveal the top five cards of your library. You may put all creature cards and\/or land cards from among them into your hand.Put the rest into your graveyard.",
    "Search your library for a card and put that card into your hand. Then shuffle your library.",
    "Target player sacrifices two creatures.",
    "Create a 5\/5 black Demon creature token with flying.You lose 2 life.",
    "Create a 4\/4 gold Dragon creature token with flying.",
    "Target player\'s life total becomes",
    "Destroy target nonland permanent.",
    "Return target permanent from a graveyard to the battlefield under your control.",
    "Create two 3\/3 green Beast creature tokens.",
    "Draw four cards, then discard two cards.",
    "Create a 2\/2 blue illusion creature token with \"When this creature becomes the target of a spell or ability, sacrifice it.\"",
    "Destroy target artifact, creature, or enchantment. Create a colorless treasure artifact token.",
    "Create a 3\/3 green dinosaur creature token with trample.",
    "Untap all pernaments you control.",
    "Gain control of target creature until end of turn. Untap it and it gains haste. At the beginning of your endstep, if that creature has a mana value of 3 or less, sacrifice it.",
    "Target creature gets +X\/+X until end of turn, where X is the number of creatures you control.",
    "Destroy target creature.",
    "Return target creature card from your graveyard to the battlefield.",
    "Create a 0\/0 colorless construct artifact creature token with \"This creature gets +1\/+1 for each artifact you control.\"",
    "Put target nonland permanent into it\'s owner\'s library third from the top.",
    "You gain 2 life and draw 2 cards.",
    "Urza, Academy Headmaster deals 3 damage to any target.",
    "Draw 2 cards.",
    "Create a 3\/3 green dog creature token with vigilance.",
    "Target creature gets -X\/-X until end of turn, where X is the number of black creatures you control.",
    "Draw a card. If you control three or more artifacts, draw three cards instead.",
    "Destroy target artifact, enchantment, or creature with flying.",
    "Put target creature or planeswalker card from a graveyard onto the battlefield under your control.",
    "Urza, Academy Headmaster deals 10 damage to target creature.",
    "Until your next turn, target artifact you control becomes a 5\/5 creature in addition to it\'s other types.",
    "Return target creature card from your graveyard to your hand.",
    "Target creature you control deals damage equal to its power to any target.",
    "Return up to two target land cards from your graveyard to the battlefield.",
    "The next spell you cast this turn cost 1 less to cast for each artifact you control as you cast it.",
    "The next spell you cast this turn cost 1 less to cast for each enchantment you control as you cast it.",
    "The next spell you cast this turn cost 1 less to cast, for each creature you control.",
    "The next spell you cast this turn cost 1 less to cast for each planeswalker you control as you cast it.",
    "Urza, Academy Headmaster deals damage to target creature or player, equal to the number of instant or sorcery cards you own in exile and in your graveyard.",
    "Destroy target nonland permanent with mana value 3 or less.",
    "Tap target creature. Put a stun counter on that creature.",
    "Look at the top 4 cards of your library, put up to 2 creature cards from among them into your hand. Then put the rest on the bottom of your library in a random order.",
    "Target player discards a card.",
    "Create a 1\/1 red Devil creatur token with \"When this creature dies, it deals 1 damage to any target.\"",
    "Return target card from your graveyard to your hand.",
    "Amass zombie",
    "Target player mills 4 cards. Then Exile each opponent\'s graveyard.",
    "Exile target creature.",
    "Destroy target tapped nonland permanent.",
    "Create a 4\/4 white Angel creature token with flying and vigilance.",
    "Create a 2\/2 white Cat Soldier creature token with \"Whenever you gain life, put a +1\/+1 counter on this creature.\"",
    "Create a 4\/4 blue Elemental Bird creature token with flying.",
    "You may put a creature card from your hand onto the battlefield.",
    "Target instant or sorcery card in your graveyard gains flashback until end of turn.",
    "Exile Target creature. It\'s controller gains life equal to its power.",
    "Return up to two target creatures to their owner\'s hand.",
    "Destroy target permanent. It\'s controller searches their library for a basic land card and puts it onto the battlefield.",
    "Destroy target nonland permanent.",
    "Destroy target creature. Draw a card.",
    "Until your next turn, whenever a creature deals damage to Urza, Academy Headmaster, destroy that creature.",
    "Create 3 food tokens.",
    "Target creature gains firststrike and haste until end of turn.",
    "Until end of turn, Urza becomes a copy of target creature you control, except it has hexproof.",
    "Return target creature to it\'s owner\'s hand. They then Exile a card from their hand.",
    "Discard all the cards in your hand, then draw that many cards plus",
    "When you cast a creature this turn, search your library for a creature with lesser mana value and put it onto the battlefield.",
    "Whenever you attack this turn, for each creature attacking create a 1\/1 white Soldier creature token that is tapped and attacking.",
    "Phase target creature out.",
    "Target creature gets -X\/-X, where X is the number of cards in your graveyard.",
    "Whenever a creature attacks this turn, put a +1\/+1 counter on it.",
    "Create a 3\/3 green Beast creature token. Then if an opponent controls more creatures than you, create another one.",
    "Each player loses life equal to the number of creatures they control.",
    "Put target creature on top of its owner\'s library.",
    "Up to two target creatures fight.",
    "Exile target permanent.",
    "Exile target artifact or creature.",
    "Target player mills 10 cards.",
    "Create a shard token (pay 2 and sacrifice this enchantment\: Scry 2, draw a card.)",
    "Deal 2 damage to target tapped creature for each card you\'ve drawn this turn.",
    "Discard up to three cards, then draw that many.",
    "Draw cards equal to the greatest power among creatures you control.",
    "Each opponent sacrifices the creature with the greatest power that they control.",
    "Return target creature card from your graveyard to the battlefield. It gains haste. Sacrifice it at the beginning of your next endstep.",
    "Create two 1\/1 colorless Soldier artifact creature tokens.",
    "Exile target nonland permanent.",
    "Each other planeswalker you control gains the abilities of Urza, Academy Headmaster until end of turn.",
    "Create a 0\/0 green and blue Fractal token. Put X +1\/+1 counters on it, where X is the number of loyalty counters among permanents you control.",
    "Put a corruption counter on target creature. You get an emblem with \"You have protection from creatures with corruption counters on them.\"",
    "You may sacrifice a creature. If you do, destroy target creature or planeswalker.",
    "Create a blue Dog Illusion creature token with \"This creature\'s power and toughness are each equal to twice the number of cards in your hand.\"",
    "Create two 2\/1 black Spider creature tokens with menace and reach.",
    "Look at the top six cards of your library.You may reveal a creature card from among them and put it into your hand.If it\'s legendary, you gain 3 life.Put the rest on the bottom of your library in a random order.",
    "Create a green Treefolk creature token with reach and \"This creature\'s power and toughness are each equal to the number of lands you control.\"",
    "Put any number of land cards from your hand onto the battlefield tapped.",
    "Create two 2\/2 green Wolf creature tokens.",
    "Look at the top three cards of your library. Put one of them into your hand and the rest on the bottom of your library in any order.",
    "Return target creature card from your graveyard to the battlefield. That creature is a black Zombie in addition to its other colors and types.",
    "Create a 1\/1 colorless Thopter artifact creature token with flying. You gain 1 life.",
    "Create a 2\/3 black Vampire creature token with flying and lifelink.",
    "Create a copy of target permanent.",
    "Until end of turn, if one or more tokens would be created under your control, twice that many of those tokens are created instead.",
    "Return target nonlegendary creature card with mana value X from your graveyard to the battlefield.",
    "Exile target tapped creature. You gain 2 life.",
    "Create a 2\/2 white Samurai creature token with vigilance.",
    "Create a 1\/1 blue Ninja creature token with \"This creature can\'t be blocked.\"",
    "Look at the top seven cards of your library. You may put a permanent card with mana value 3 or less from among them onto the battlefield with a shield counter on it. Put the rest on the bottom of your library in a random order.",
    "Create a 4\/4 green Rhino Warrior creature token.",
    "Exile the top card of your library. Create a number of 1\/1 blue Faerie Dragon creature tokens with flying equal to that card's mana value.",
    "Sacrifice a creature. When you do, Urza deals X damage to any target, where X is that creature's power. If the sacrificed creature was a construct, draw X cards.",
    "You get an emblem with \"Whenever you cast a spell you don't own, create a 3\/3 black Demon creature token.\"",
    "Target player draws two cards. Until your next turn, instant, sorcery, and planeswalker spells that player casts cost {2} less to cast.",
    "Urza deals 3 damage to each tapped creature target player controls.",
    "Look at the top three cards of your library. Exile one face down and put the rest on the bottom of your library in any order. For as long as it remains exiled, you may look at that card and you may cast it if it's a creature spell.",
    "Create a 2\/2 red and green Satyr creature token with haste.",
    "Mill two cards, then you may return a creature card from your graveyard to your hand.",
    "Exile another target permanent you own, then return it to the battlefield under your control.",
    "Each opponent exiles two cards from their hand.",
    "Search your library for a Dragon card, reveal it, put it into your hand, then shuffle.",
    "Pay any amount of mana. Look at that many cards from the top of your library, then put one of those cards into your hand and the rest on the bottom of your library in a random order.",
    "Target player sacrifices a creature.",
    "Choose target creature an opponent controls. Whenever you attack this turn, Urza deals damage equal to the number of attacking creatures to that creature.",
    "Exile the top two cards of your library. Choose one of them. You may play that card this turn.",
    "Distribute three +1\/+1 counters among up to three target creatures. They gain vigilance until end of turn.",
    "Urza deals damage equal to the number of loyalty counters on him to a creature or player.",
    "Return a card with mana value 2 or less from your graveyard to your hand.",
    "Create two 1\/1 colorless Thopter artifact creature tokens with flying. They gain haste until end of turn.",
    "Create a 2\/2 blue Spirit creature token with vigilance and \"Whenever you draw a card, put a +1\/+1 counter on this creature.\"",
    "Urza, Academy Headmaster gains \"Whenever you draw a card, put a loyalty counter on Urza, Academy Headmaster.\"",
    "Create a 2\/2 white Samurai creature token with double strike.",
    "Target player mills three cards. Then if a graveyard has twenty or more cards in it, you draw three cards. Otherwise, you draw a card.",
    "Target creature becomes a Treasure artifact with \"{T}, Sacrifice this artifact\: Add one mana of any color\" and loses all other card types and abilities.",
    "Urza deals damage to target creature equal to the number of Mountains you control.",
    "Destroy target artifact or enchantment.",
    "Create a 2\/2 colorless Drone artifact creature token with deathtouch and \"When this creature leaves the battlefield, each opponent loses 2 life and you gain 2 life.\"",
    "Exile target creature or enchantment. If it wasn\'t an Aura, create a token that\'s a copy of it, except it\'s a 1\/1 white Spirit creature with flying in addition to its other types.",
    "You draw two cards. Then each opponent may scry",
    "Create a 3\/3 green Phyrexian Beast creature token with toxic",
    "Mill three cards, then you may return a creature card with mana value 2 or less from your graveyard to the battlefield.",
    "Put two +1\/+1 counters on target creature. It becomes an Angel in addition to its other types and gains flying.",
    "Mill three cards. You may put a permanent card from among the milled cards into your hand.",
    "You get an emblem with \"Knights you control get +1\/+0 and have ward {1}.\"",
    "Tap any number of untapped creatures you control. When you do, shuffle target nonland permanent an opponent controls with mana value X or less into its owner\'s library, where X is the number of creatures tapped this way.",
    "You may put an Equipment card from your hand or graveyard onto the battlefield.",
    "Untap up to four target permanents.",
    "Create a 5\/5 black Demon creature token with flying. You lose 2 life.",
    "Sacrifice an artifact. If you do, return target artifact card from your graveyard to the battlefield.",
    "Create X treasure tokens, where X is the number of artifacts your opponents control.",
    "Destroy target artifact or enchantment.",
    "You draw X cards and Commodore Guff deals X damage to each opponent, where X is the number of planeswalkers you control.",
    "Choose left or right. Until your next turn, each player may attack only the nearest opponent in the last chosen direction and planeswalkers controlled by that opponent.",
    "For each opponent, return up to one target nonland permanent that player controls to its owner's hand.",
    "Remove a loyalty counter from each of any number of permanents you control. Exile that many cards from the top of your library. You may play them this turn.",
    "Destroy target permanent that\'s one or more colors.",
    "Put a +1\/+1 counter on each creature you control and a loyalty counter on each other planeswalker you control.",
    "Until end of turn, Urza becomes a 6\/6 Human Soldier creature that's still a planeswalker. Prevent all damage that would be dealt to him this turn.",
    "Exile target creature with power 4 or greater.",
    "Target player draws two cards.",
    "Reveal the top three cards of your library. An opponent separates those cards into two piles. Put one pile into your hand and the other on the bottom of your library in any order.",
    "Create a token that\'s a copy of Urza, Academy Headmaster, except it\'s not legendary and its starting loyalty is 1",
    "Look at the top four cards of your library. You may reveal a noncreature, nonland card from among them and put it into your hand. Put the rest on the bottom of your library in a random order.",
    "Until the beginning of your next turn, each opponent can\'t draw more than one card each turn.",
    "Urza deals 3 damage to each non-Elemental creature.",
    "Urza deals 4 damage to target creature.",
    "Create a 4\/4 red Dragon creature token with flying.",
    "Exile target creature or enchantment you don't control until target enchantment you control leaves the battlefield.",
    "Exile target enchantment, tapped artifact, or tapped creature.",
    "Draw a card, then you may discard a card. When you discard a nonland card this way, Urza deals damage equal to that card\'s mana value to target creature or planeswalker.",
    "Target artifact you control becomes a copy of another target artifact or creature you control until end of turn, except it\'s an artifact in addition to its other types.",
    "Create two 1\/1 black Nightmare creature tokens with \"At the beginning of combat on your turn, if a card was put into exile this turn, put a +1\/+1 counter on this creature.\"",
    "Discover 4",
    "You get an emblem with \"Whenever you cast a spell from exile, this emblem deals 2 damage to each opponent and you gain 2 life.",
    "You get an emblem with \"Creatures you control get +1\/+0.\"",
    "You may reveal an artifact card you own from outside the game or choose a face-up artifact card you own in exile. Put that card into your hand.",
    "Exile target nonland permanent.",
    "Each player sacrifices two creatures.",
    "Target creature you control fights another target creature.",
    "Exile target nonland permanent with mana value 1 or less.",
    "Destroy target creature or planeswalker.",
    "Return up to one target artifact, creature, or enchantment to its owner's hand. Draw a card.",
    "Destroy all creatures with power 4 or greater.",
    "Target artifact becomes an artifact creature.If it isn't a Vehicle, it has base power and toughness 4\/4",
    "Exile target creature you control. For each other player, exile up to one target creature that player controls.",
    "Create a 3\/3 green Elk creature token.",
    "Create a 2\/1 white Cat Warrior creature token. When you do, if you control a red permanent other than Urza, Academy Headmaster he deals damage equal to the number of creatures you control to any target.",
    "Search your library for a card, then shuffle and put that card on top.",
    "Draw a card. You may play an additional land this turn.",
    "When you next cast an instant or sorcery spell from your hand this turn, it gains rebound. (Exile the spell as it resolves. At the beginning of your next upkeep, you may cast that card from exile without paying its mana cost.)",
    "You may cast target instant or sorcery card from your graveyard this turn. If that spell would be put into your graveyard, exile it instead.",
    "Create Ashaya, the Awoken World, a legendary 4\/4 green Elemental creature token.",
    "Reveal the top four cards of your library. You may put a creature card and\/or a land card from among them into your hand. Put the rest into your graveyard.",
    "Tap up to two target nonland permanents. They don't untap during their controller's next untap step.",
    "You may sacrifice an artifact. If you do, destroy target artifact or creature.",
    "Each opponent discards a card and you draw a card.",
    "Choose up to two target creatures. For each of them, put a number of +1\/+1 counters on it equal to the number of colors it is.",
];
const ability3 = [

    "Urza deals 7 damage to target player or planeswalker.That player or that planeswalker\'s controller discard seven cards, then sacrifices seven permanents.",
    "You get an emblem with \"If a source would deal damage to you or a planeswalker you control, prevent all but 1 of that damage.\"",
    "Destroy all lands target player controls.",
    "Create X 2\/2 white Cat creature tokens, where X is your life total.",
    "You gain 100 life.",
    "You get an emblem with \"Whenever a creature you control dies venture into the dungeon\"",
    "Urza deals 10 damage to target player or planeswalker and each creature that player or that planeswalker\'s controller controls.",
    "You get an emblem with \"Creatures you control have double strike, trample, hexproof, and haste.\"",
    "You get an emblem with \"Artifacts, creatures, enchantments, and lands you control have indestructible.\"",
    "Create a 6\/6 green Wurm creature token for each land you control.",
    "Each player shuffles their hand and graveyard into their library. You draw seven cards",
    "Destroy up to three target creatures and\/or other planeswalkers. Return each card put into a graveyard this way to the battlefield under your control.",
    "You get an emblem with \"Whenever you cast a spell, exile target permanent.\"",
    "You get an emblem with \"Whenever a creature enters the battlefield under your control, you may have it fight target creature.\" Then create three 8\/8 blue Octopus creature tokens.",
    "You control target player during that player\'s next turn.",
    "Exile all cards from target player\'s library, then that player shuffles their hand into their library.",
    "Create three 1\/1 black Assassin creature tokens with \"Whenever this creature deals combat damage to a player, that player loses the game.\"",
    "Put all creature cards from all graveyards onto the battlefield under your control.",
    "You gain X life and draw X cards, where X is the number of lands you control.",
    "Flip five coins. Take an extra turn after this one for each coin that comes up heads.",
    "You gain 7 life, draw seven cards, then put up to seven permanent cards from your hand onto the battlefield.",
    "Create two tokens that are copies of Urza, Academy Headmaster, except they\'re are not legendary.",
    "Up to one target player\'s life total becomes 1",
    "Urza, Academy Headmaster deals damage equal to the greatest power among creatures you control, divided as you choose among any number of targets.",
    "Gain control of up to three target creatures.",
    "Each opponent loses life equal to the number of cards in their graveyard.",
    "You get an emblem with \"You may play cards from among face up cards your opponents own in exile and you may spend mana as though it was mana of any color to cast those spells.\"",
    "You get an emblem with \"Whenever a creature enters the battlefield under your control, you may draw a card.",
    "Until end of turn, creatures you control gain deathtouch and \"Whenever this creature deals combat damage to a player, that player loses the game.\"",
    "Destroy all creatures target player controls. Urza, Academy Headmaster deals damage equal to their total power to that player.",
    "You get an emblem with \"Whenever you draw a card, exile target permanent an opponent controls.\"",
    "Take an extra turn after this one.",
    "Urza, Academy Headmaster deals 10 damage to target player and each creature and planeswalker that player controls.",
    "Tap all permanents your opponents control, then take an extra turn after this one.",
    "Until end of turn, target creature gets +X\/+X and trample, where X is the number of lands you control.",
    "You may cast creature spells from your graveyard this turn.",
    "You get an emblem with \"At the beginning of your endstep, search your library for a permanent card, put it onto the battlefield, then shuffle your library.\"",
    "Create 4 5\/5 red Dragon creature tokens with flying.",
    "You get an emblem with \"Creatures you control get +2\/+2 and have vigilance, Trample and indestructible.\"",
    "Exile all but the bottom card of target player\'s library.",
    "Distribute X +1\/+1 counters among any number of target creatures you control, where X is your life total.",
    "Put any number of cards from your hand face down, they are 5\/5 colorless artifact creatures.",
    "Destroy up to two target creatures, then put up to two target creature cards from graveyards onto the battlefield under your control.",
    "Search your library for any number of creature cards. Target opponent separates those cards into two piles. One pile is put onto the battlefield under your control, and the other is shuffled back into your library.",
    "Creatures you control gain +4\/+4 and trample until end of turn.",
    "Return all non-aura enchantment and artifact cards from your graveyard to the battlefield, then do the same for auras.",
    "Destroy up to six target nonland permanents, then create 6 2\/2 green Cat creature tokens with forestwalk.",
    "For each artifact you control, create a token copy of it. They gain haste. Exile those tokens at the beginning of your next endstep.",
    "For each creature you control, create a token copy of it. They gain haste. Exile those tokens at the beginning of your next endstep.",
    "You get an emblem with \"Whenever you cast an instant or sorcery, this emblem deals any target 2 damage and you draw two cards.\"",
    "Draw seven cards, Urza, Academy Headmaster deals 7 damage up to 7 targets.",
    "Put X +1\/+1 counters on each creature you control, where X is the number of creature cards in your graveyard.",
    "Target player skips their next untap step.",
    "Draw seven cards. Then if your library has no cards in it, you win the game.",
    "Exile the top 7 cards of your library. You can play them this turn.",
    "You get an emblem with \"Your lands are indestructible.\"",
    "Search your library for any number of land cards and put them onto the battlefield tapped.",
    "Until your next untap step, whenever you tap a land to produce mana, add an additional mana of any color that land could produce.",
    "Exile Urza, Academy Headmaster and each creature your opponents control.",
    "Creatures can\'t be blocked this turn.",
    "Exile the top 10 cards of your library. Put all permanent cards from among them onto the battlefield.",
    "You get an emblem with \"If you control a creature any damage that you receive that would reduce your life total to less than 1 reduces it to 1 instead.\"",
    "You get an emblem with \"Islands you control have \'(tap)\: Draw a card\' \"",
    "You may reveal a card you own in exile, put that card into your hand.",
    "Creatures you control gain flying and doublestrike until end of turn.",
    "Until end of turn each nontoken creature you control gains \"Sacrifice this creature\: Gain control of target creature.\"",
    "Urza deals 10 damage to target player and each creature they control.",
    "Target creature gains +10\/+10 and trample until end of turn.",
    "Create 3 1\/1 black Assassin creature tokens with Deathtouch and have \"Whenever this creature deals combat damage to a player, that player loses the game.\"",
    "You get an emblem with \"creatures you control get +3\/+3 and have trample.\"",
    "Exchange control of an artifact or creature you control with an artifact or creature an opponent controls.",
    "Draw 4 cards. Urza deals damage equal to the number of cards in your hand to any target.",
    "Until end of turn, each creature you control has base power and toughness 10\/",
    "Gain control of all creatures until end of turn. Creatures you control gain haste.",
    "You may cast up to three target face-up cards from exile without paying their mana costs.",
    "Urza deals X damage to each creature, where X is the number of creatures on the battlefield.",
    "You get an emblem with \"At the beginning of your endstep create a 1\/1 white Soldier token, then put a +1\/+1 counter on each creature you control.\"",
    "Take two extra turns after this one.",
    "You get an emblem with \"At the beginning of combat on your turn, put a creature card from a graveyard onto the battlefield under your control. It gains haste.\"",
    "You may search your library for any number of instant and\/or sorcery cards, reveal them, then put them into your hand. Shuffle your library.",
    "You get an emblem with\" At the beginning of your endstep, you may search your library for a creature card. Put it onto the battlefield. Shuffle your library.\"",
    "Creatures you control gain +2\/+2 and flying until end of turn.",
    "Target opponent loses 2 life for each creature card in their graveyard.",
    "Each creature creature target opponent controls phases out, they can\'t phase back in till the end of your next turn.",
    "Discard your hand. Draw seven. Until the end of your turn, you may cast spells from your hand without paying their Mana costs.",
    "Until end of turn, creatures you control gain \"You may assign combat damage as though this creature wasn\'t blocked.\"",
    "Set aside all cards in exile. Restart the game. Starting with you each player may cast each spell and play each land they own in Exile from the last game.",
    "You may put a creature from your hand or graveyard onto the battlefield with 2 +1\/+1 counters on it. It gains hexproof until the beginning of your next turn.",
    "Gain control of all commanders. Put all commanders from the command zone onto the battlefield under your control.",
    "Urza, deals 18 damage divided among any number of targets.",
    "You get an emblem with \"Whenever you cast a creature spell, it gains haste until end of turn, then draw two cards.\"",
    "You get an emblem with \"At the beginning of your upkeep, you may cast a legendary spell from your hand, graveyard, or from among cards you own in exile.\"",
    "Exile all other permanents.",
    "Target opponent gets an emblem with \"Whenever a player draws a card, you lose 2 life.\"",
    "You get an emblem with \"You can cast instants or sorcery spells from your graveyard. If a card would be put into your graveyard from a spell cast this way exile it instead.",
    "You get an emblem with \"Magecraft-whenever you cast or copy an instant or sorcery, each opponent loses 2 life and you gain 2 life.\"",
    "Each opponent may discard a card. If they don\'t they lose 3 life. Repeat this process 6 times.",
    "Return all nonland pernaments to their owner\'s hand, except for Urza, Academy Headmaster. Then each player\'s life total becomes 1",
    "You get an embel with \"Whenever a creature enters the battlefield under your control, it deals damage equal to its power to any target.\"",
    "Artifacts and planeswalkers you control gain indestructible until end of turn. Destroy all nonland permanents.",
    "You get an emblem with \"At the beginning of each players upkeep amass orcs 2\"",
    "You may search your library for an instant or sorcery that shares a color with a legendary permanent you control. Then you may cast that spell without paying it\'s mana cost.",
    "You may put an artifact from your hand or graveyard onto the battlefield.",
    "Each opponent loses life equal to the number of creature cards in your graveyard.",
    "Exchange your hand and library, then shuffle. You get an emblem with \"You have no maximum hand size.\"",
    "You get an emblem with \"Whenever an opponent is dealt combat damage by one or more creatures you control, if that player lost less than 8 life this turn, they lose life equal to the difference.\"",
    "You get an emblem with \"At the end of the first combat phase on your turn, untap target creature you control. After this phase, there is an additional combat phase.\"",
    "You get an emblem with \"Creatures you control have trample and haste and get + 2\/+2 for each differently named dungeon you've completed.\"",
    "Return all permanent cards from your graveyard to your hand. You get an emblem with \"You have no maximum hand size.\"",
    "You get an emblem with \"Untap all permanents you control during each opponent\'s untap step\" and \"You draw a card during each opponent\'s draw step.\"",
    "You get an emblem with \"You can activate loyalty abilities of planeswalkers you control twice each turn instead of once.\"",
    "Destroy all non-Zombie creatures.",
    "Look at the top ten cards of your library. Put five of them into your hand and the rest on the bottom of your library in a random order.",
    "Urza deals 13 damage to any target. You gain 13 life.",
    "Exile the top five cards of your library. You may cast red spells from among them this turn. You get an emblem with \"Whenever you cast a red spell, this emblem deals X damage to any target, where X is the amount of mana spent to cast that spell.\"",
    "Exile all cards from all graveyards, then create a 1\/1 white Spirit creature token with flying for each card exiled this way.",
    "You get an emblem with \"Whenever a creature dies, return it to the battlefield under your control at the beginning of the next end step.\"",
    "You get an emblem with \"Whenever a creature you control deals combat damage to a player, search your library for a blue or black creature card, put it onto the battlefield, then shuffle.\"",
    "Put five +1\/+1 counters on each creature you control and five loyalty counters on each other planeswalker you control.",
    "Create five 3\/3 white Angel creature tokens with flying.",
    "Target player draws seven cards and loses 7 life.",
    "You get an emblem with \"Whenever you scry, the next instant or sorcery spell you cast this turn costs X less to cast, where X is the number of cards looked at while scrying this way.\"",
    "Target player gets an emblem with \"Whenever you cast an instant or sorcery spell, copy it. You may choose new targets for the copy.\"",
    "Target player gets an emblem with \"Whenever you activate an ability that isn\'t a mana ability, copy it. You may choose new targets for the copy.\"",
    "You get an emblem with \"You may cast creature spells as though they had flash.\"",
    "Exile the top seven cards of your library. You may put any number of creature and\/or land cards from among them onto the battlefield.",
    "You get an emblem with \"At the beginning of your end step, create X 2\/2 black Zombie creature tokens, where X is two plus the number of Zombies you control.\"",
    "Choose left or right. Each player gains control of all nonland permanents other than Urza, Academy Headmaster controlled by the next player in the chosen direction.",
    "Exile each nonland permanent your opponents control.",
    "You get an emblem with \"Instant and sorcery cards in your graveyard have retrace.\" (You may cast instant and sorcery cards from your graveyard by discarding a land card in addition to paying their other costs.)",
    "Destroy all non-Dragon creatures.",
    "You get an emblem with \"Tap an untapped artifact you control\: This emblem deals 1 damage to any target.\"",
    "Separate all permanents target player controls into two piles. That player sacrifices all permanents in the pile of their choice.",
    "You get an emblem with \"Whenever you cast a red instant or sorcery spell, copy it twice. You may choose new targets for the copies.\"",
    "You get an emblem with \"Whenever you cast a creature or planeswalker spell, target opponent gets two poison counters.\"",
    "You may activate Urza, Academy Headmaster\'s loyalty ability two more times this turn.",
    "You get an emblem with \"Artifact creatures you control get +1\/+1 and \"Artifact spells you cast cost {1} less to cast.\"",
    "Target opponent chooses a permanent they control and returns it to its owner's hand. Then they shuffle each nonland permanent they control into its owner\'s library.",
    "For each player, choose a creature that player controls. Each player sacrifices all creatures they control not chosen this way.",
    "Each player votes for Shahrazad or Time Walk. If Shahrazad gets more votes, then players play a Magic subgame, using their libraries as their decks. Each player who doesn\'t win the subgame loses half their life, rounded up. If time Walk gets more votes or the votes are tied. You take an extra turn after this one.",
    "Target player mills 40 cards.",
    "If target player has fewer than nine poison counters, they get a number of poison counters equal to the difference.",
    "You get an emblem with \"Whenever a Mountain enters the battlefield under your control, this emblem deals 4 damage to any target.\"",
    "Until end of turn, creatures you control get +1\/+1 for each Forest you control and gain trample.",
    "Return all nonland permanent cards with mana value 3 or less from your graveyard to the battlefield.",
    "Urza deals X damage divided as you choose among any number of target creatures and\/or planeswalkers, where X is the greatest power among creatures you controlled as you activated this ability.",
    "You get an emblem with \"Whenever you cast an instant or sorcery spell, copy it. You may choose new targets for the copy. This ability triggers only once each turn.\"",
    "You get an emblem with \"You may play lands and cast permanent spells from your graveyard.\"",
    "You get an emblem with \"Lands you control have \"{T}\: Add one mana of any color.\"",
    "Create a colorless Equipment artifact token named Stoneforged Blade. It has indestructible, \"Equipped creature gets +5\/+5 and has double strike,\" and equip {0}",
    "You get an emblem with \"You may activate loyalty abilities of planeswalkers you control on any player\'s turn any time you could cast an instant.\"",
    "You get an emblem with \"Sacrifice a creature: You gain X life and draw X cards, where X is the sacrificed creature's power.\"",
    "You get an emblem with \"Whenever an artifact is put into your graveyard from the battlefield, return that card to the battlefield at the beginning of the next end step.\"",
    "Draw a card for each green creature you control.",
    "Target artifact you control becomes a 9\/9 Construct artifact creature and gains vigilance, indestructible, and \"This creature can\'t be blocked.\"",
    "You get an emblem with \"Prevent all noncombat damage that would be dealt to you and other permanents you control.\"",
    "Target player mills twenty cards.",
    "For each player, search that player's library for a nonland card and exile it, then that player shuffles. You may cast those cards without paying their mana costs.",
    "You get an emblem with \"Whenever you cast a spell, this emblem deals 5 damage to any target.\"",
    "Return all enchantment cards from your graveyard to the battlefield.",
    "Search your library for an artifact or creature card, put it onto the battlefield, then shuffle. It gains haste. Return it to your hand at the beginning of the next end step.",
    "You get an emblem with \"Whenever you cast a noncreature spell, this emblem deals 2 damage to any target.\"",
    "Target player exiles the top X cards of their library, where X is the total mana value of cards you own in exile.",
    "Exile any number of target cards from your graveyard. Add {R} for each card exiled this way. You may play those cards this turn.",
    "Destroy up to three target creatures and\/or other planeswalkers. Return each card put into a graveyard this way to the battlefield under your control.",
    "Each opponent chooses a permanent they control of each permanent type and sacrifices the rest.",
    "You get an emblem with \"Whenever a creature you control dies, draw a card.\"",
    "You get an emblem with \"Creatures you control have double strike, trample, hexproof, and haste.\"",
    "Urza deals damage to target player equal to the number of cards that player owns in exile and you gain that much life.",
    "Each opponent who doesn\'t control a legendary creature or planeswalker loses the game.",
    "You get an emblem with \"Planeswalkers you control have all loyalty abilities of all other planeswalkers on the battlefield.\"",
    "You get an emblem with, \"Each opponent can cast spells only any time they could cast a sorcery.\"",
    "You get an emblem with \"Creatures you control get + 2\/+2 and have flying.\"",
    "You get an emblem with \"Whenever an artifact you control becomes tapped, draw a card.\"",
    "For each other nonland permanent you control, create a token that\'s a copy of that permanent.",
    "Until end of turn, whenever you cast a spell, copy it. You may choose new targets for the copy.",
    "Each opponent chooses an artifact, a creature, an enchantment and a planeswalker from among the nonland permanents they control, then sacrifices the rest.",
    "Create a white Avatar creature token. It has \"This creature\'s power and toughness are each equal to your life total.\"",
    "Destroy all other permanents except for lands and tokens.",
    "Create 6 copies of target permanent. If that permanent was a creature. Those tokens gain haste.",
    "Any number of target players each draw twenty cards.",
    "Exile all cards from all opponents\' hands and graveyards.",
    "Target opponent gets an emblem with \"Whenever a creature attacks you, it gets +5\/+5 and gains trample until end of turn.\"",
    "You get an emblem with \"At the beginning of your draw step, draw two additional cards\" and \"At the beginning of your end step, discard your hand.\"",
    "You get an emblem with \"Whenever you cast a spell, target opponent mills five cards.\"",
    "Urza deals 6 damage to each opponent. Each player dealt damage this way gets an emblem with \"At the beginning of your upkeep, this emblem deals 3 damage to you.\"",
    "Untap up to six target lands. They become 6\/6 Elemental creatures. They\'re still lands.",
    "You get an emblem with \"Whenever a creature enters the battlefield under your control, you may have it fight target creature.\" Then create three 8\/8 blue Octopus creature tokens.",
    "You get an emblem with \"Whenever an opponent casts their first spell each turn, counter that spell.\"",
    "You get an emblem with \"Creatures you control have haste and \‘{T}\: This creature deals damage equal to its power to any target.\"",
    "Create a number of 1\/1 black Vampire Knight creature tokens with lifelink equal to the highest life total among all players.",
    "You get an emblem with \"Whenever you cast a spell that targets one or more permanents, gain control of those permanents.\"",
    "Draw three cards. You get an emblem with \"You may cast spells from your hand without paying their mana costs.\"",
    "Choose target artifact card in a graveyard or artifact on the battlefield. Create three tokens that are copies of it.",
    "You get an emblem with \"Whenever a land enters the battlefield under your control, you may draw a card.\"",
    "You get an emblem with \"Your opponents can\'t untap more than two permanents during their untap steps.\"",
    "Return target multicolored card from your graveyard to your hand. If that card was all colors, draw a card and create two Treasure tokens"];

// Function to generate a ability.
function generateRandomParagraph(paragraphs) {
    const randomIndex = Math.floor(Math.random() * paragraphs.length);
    return paragraphs[randomIndex];
}
document.getElementById('button1').addEventListener('click', function () {
    const messagePlaceholder = document.getElementById('message-placeholder');
    messagePlaceholder.textContent = generateRandomParagraph(ability1);
});

document.getElementById('button2').addEventListener('click', function () {
    const messagePlaceholder = document.getElementById('message-placeholder');
    messagePlaceholder.textContent = generateRandomParagraph(ability2);
});

document.getElementById('button3').addEventListener('click', function () {
    const messagePlaceholder = document.getElementById('message-placeholder');
    messagePlaceholder.textContent = generateRandomParagraph(ability3);
});

